name: Windows - Build Dependencies (vcpkg)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: '4ebb30167f14487dcb71fac13efbf63273ab6a3f'
          vcpkgDirectory: '${{ runner.workspace }}/vcpkg'

      - name: Force Release Build Only
        run: |
          Add-Content -Path "${{ runner.workspace }}/vcpkg/triplets/x64-windows.cmake" -Value "set(VCPKG_BUILD_TYPE release)" -Encoding ascii

      - name: Install Dependencies
        shell: bash
        run: |
          vcpkg install \
            bdwgc \
            boost \
            dav1d \
            doctest \
            expat \
            ffmpeg \
            glew \
            imath \
            libatomic-ops \
            libjpeg-turbo \
            libpng \
            libraw \
            libwebp \
            nanobind \
            opencolorio \
            openexr \
            openimageio[ffmpeg,libraw,freetype,opencolorio,openjpeg,webp] \
            openjpeg \
            openjph \
            openssl \
            pcre2 \
            spdlog \
            tiff \
            yaml-cpp \
            zlib \
            --triplet x64-windows

      - name: Export Binary Archive
        shell: bash
        run: |
          vcpkg export \
            bdwgc \
            boost \
            dav1d \
            doctest \
            expat \
            ffmpeg \
            glew \
            imath \
            libatomic-ops \
            libjpeg-turbo \
            libpng \
            libraw \
            libwebp \
            nanobind \
            opencolorio \
            openexr \
            openimageio \
            openjpeg \
            openjph \
            openssl \
            pcre2 \
            spdlog \
            tiff \
            yaml-cpp \
            zlib \
            --raw --output-dir=exported_deps --output=utv-deps-windows-x64

      - name: Package MSI Installer (CPack WiX)
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" ..
          cpack -G WIX

      - name: Upload to Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload windows-x64 build/OpenUTVDeps-2026.1.0-win64.msi --clobber || gh release create windows-x64 build/OpenUTVDeps-2026.1.0-win64.msi -t "Windows x64 Dependencies" -n "Rolling release powered by vcpkg"
